name: "novamart"
version: "0.1.0"
config-version: 2

profile: "novamart"

model-paths: ["models"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  novamart:
    staging:
      +materialized: view
      +schema: staging
    gold:
      +materialized: table
      +schema: gold
      +file_format: delta

snapshots:
  novamart:
    +target_schema: snapshots
    +file_format: delta

vars:
  # date-spine bounds for dim_date
  date_start: "2021-01-01"
  date_end: "2026-12-31"
